# Generated by Django 6.0.4 on 2026-06-29 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRevisionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=True)),
                ('completion_pct', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('migrated_from_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migrated_to_progress', to='tasks.taskrevision')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='tasks.taskrevision')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_progress', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_revision_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckpointProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('in_progress', 'In progress'), ('done', 'Done')], default='locked', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='tasks.taskcheckpoint')),
                ('revision_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='progress.taskrevisionprogress')),
            ],
            options={
                'ordering': ['checkpoint__order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HintUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_index', models.PositiveSmallIntegerField()),
                ('points_spent', models.PositiveSmallIntegerField(default=0)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_usages', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'indexes': [models.Index(fields=['user', 'task'], name='progress_hi_user_id_100cb4_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'task', 'hint_index'), name='progress_unique_hint_usage'), models.CheckConstraint(condition=models.Q(('hint_index__gte', 1)), name='progress_hint_index_positive')],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(default=1)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['captured_at', 'rank'],
                'indexes': [models.Index(fields=['captured_at', 'rank'], name='progress_le_capture_46fa27_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rank__gte', 1)), name='progress_rank_positive')],
            },
        ),
        migrations.CreateModel(
            name='TaskAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.PositiveIntegerField(default=1)),
                ('verdict', models.CharField(choices=[('failed', 'Failed'), ('passed', 'Passed'), ('error', 'Error')], default='failed', max_length=10)),
                ('diagnostics', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'task', '-created_at'], name='progress_ta_user_id_72d6aa_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'task', 'attempt_no'), name='progress_unique_attempt_number')],
            },
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_awarded', models.PositiveSmallIntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['user', '-completed_at'], name='progress_ta_user_id_630f2f_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'task'), name='progress_unique_completion'), models.CheckConstraint(condition=models.Q(('points_awarded__gte', 0)), name='progress_points_awarded_non_negative')],
            },
        ),
        migrations.AddIndex(
            model_name='taskrevisionprogress',
            index=models.Index(fields=['user', 'task', 'is_current'], name='progress_ta_user_id_17cce1_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskrevisionprogress',
            constraint=models.UniqueConstraint(fields=('user', 'task', 'revision'), name='progress_unique_user_task_revision_progress'),
        ),
        migrations.AddConstraint(
            model_name='taskrevisionprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('user', 'task'), name='progress_single_current_revision_progress'),
        ),
        migrations.AddConstraint(
            model_name='taskrevisionprogress',
            constraint=models.CheckConstraint(condition=models.Q(('completion_pct__gte', 0), ('completion_pct__lte', 100)), name='progress_revision_completion_pct_range'),
        ),
        migrations.AddIndex(
            model_name='checkpointprogress',
            index=models.Index(fields=['revision_progress', 'status'], name='progress_ch_revisio_a5f6b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='checkpointprogress',
            constraint=models.UniqueConstraint(fields=('revision_progress', 'checkpoint'), name='progress_unique_checkpoint_progress'),
        ),
    ]
