# Generated by Django 6.0.4 on 2026-04-24 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
        ('tasks', '0002_taskcheckpoint_taskrevision_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckpointProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('in_progress', 'In progress'), ('done', 'Done')], default='locked', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['checkpoint__order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskRevisionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=True)),
                ('completion_pct', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='hintusage',
            new_name='progress_hi_user_id_100cb4_idx',
            old_name='progress_hu_user_id_1dc456_idx',
        ),
        migrations.RenameIndex(
            model_name='leaderboardsnapshot',
            new_name='progress_le_capture_46fa27_idx',
            old_name='progress_lb_captured_2be9a6_idx',
        ),
        migrations.RenameIndex(
            model_name='taskattempt',
            new_name='progress_ta_user_id_72d6aa_idx',
            old_name='progress_ta_user_id_53bfd2_idx',
        ),
        migrations.RenameIndex(
            model_name='taskcompletion',
            new_name='progress_ta_user_id_630f2f_idx',
            old_name='progress_tc_user_id_eb74de_idx',
        ),
        migrations.AddField(
            model_name='checkpointprogress',
            name='checkpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='tasks.taskcheckpoint'),
        ),
        migrations.AddField(
            model_name='taskrevisionprogress',
            name='migrated_from_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migrated_to_progress', to='tasks.taskrevision'),
        ),
        migrations.AddField(
            model_name='taskrevisionprogress',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='tasks.taskrevision'),
        ),
        migrations.AddField(
            model_name='taskrevisionprogress',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_progress', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='taskrevisionprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_revision_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkpointprogress',
            name='revision_progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='progress.taskrevisionprogress'),
        ),
        migrations.AddIndex(
            model_name='taskrevisionprogress',
            index=models.Index(fields=['user', 'task', 'is_current'], name='progress_ta_user_id_17cce1_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskrevisionprogress',
            constraint=models.UniqueConstraint(fields=('user', 'task', 'revision'), name='progress_unique_user_task_revision_progress'),
        ),
        migrations.AddConstraint(
            model_name='taskrevisionprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('user', 'task'), name='progress_single_current_revision_progress'),
        ),
        migrations.AddConstraint(
            model_name='taskrevisionprogress',
            constraint=models.CheckConstraint(condition=models.Q(('completion_pct__gte', 0), ('completion_pct__lte', 100)), name='progress_revision_completion_pct_range'),
        ),
        migrations.AddIndex(
            model_name='checkpointprogress',
            index=models.Index(fields=['revision_progress', 'status'], name='progress_ch_revisio_a5f6b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='checkpointprogress',
            constraint=models.UniqueConstraint(fields=('revision_progress', 'checkpoint'), name='progress_unique_checkpoint_progress'),
        ),
    ]
