# Generated by Django 6.0.4 on 2026-06-29 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['number'],
                'constraints': [models.CheckConstraint(condition=models.Q(('number__gte', 1), ('number__lte', 9)), name='tasks_level_number_1_9')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('platform', models.CharField(choices=[('github', 'GitHub')], default='github', max_length=10)),
                ('order', models.PositiveSmallIntegerField()),
                ('points', models.PositiveSmallIntegerField()),
                ('validator_cmd', models.CharField(default='python validator.py', max_length=255)),
                ('success_message', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='tasks.level')),
            ],
            options={
                'ordering': ['level__number', 'platform', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('manifest', 'Manifest'), ('start_repo', 'Start repository'), ('validator', 'Validator'), ('hint', 'Hint'), ('theory', 'Theory')], max_length=20)),
                ('path', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='tasks.task')),
            ],
            options={
                'ordering': ['task__level__number', 'task__order', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('objective', models.TextField()),
                ('steps', models.JSONField(blank=True, default=list)),
                ('expected_state', models.TextField(blank=True)),
                ('validator_notes', models.TextField(blank=True)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='tasks.task')),
            ],
            options={
                'ordering': ['task__level__number', 'task__order', '-version', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('mapping_key', models.CharField(blank=True, default='', max_length=120)),
                ('command_hint', models.CharField(blank=True, max_length=255)),
                ('success_criteria', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='tasks.taskrevision')),
            ],
            options={
                'ordering': ['revision__task__level__number', 'revision__task__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TheoryBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content_md', models.TextField()),
                ('diagram_mermaid', models.TextField(blank=True)),
                ('sandbox_preset', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theory', to='tasks.level')),
            ],
            options={
                'ordering': ['level__number'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['level', 'platform', 'order'], name='tasks_task_level_i_f94ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['slug'], name='tasks_task_slug_820535_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['platform'], name='tasks_task_platfor_9de46d_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('level', 'platform', 'order'), name='tasks_unique_level_platform_order'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('points__gte', 1)), name='tasks_points_positive'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 1)), name='tasks_order_positive'),
        ),
        migrations.AddIndex(
            model_name='taskasset',
            index=models.Index(fields=['task', 'asset_type'], name='tasks_taska_task_id_44cb82_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskasset',
            constraint=models.CheckConstraint(condition=models.Q(('sort_order__gte', 1)), name='tasks_asset_order_positive'),
        ),
        migrations.AddIndex(
            model_name='taskrevision',
            index=models.Index(fields=['task', 'is_active'], name='tasks_taskr_task_id_7b7779_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskrevision',
            constraint=models.UniqueConstraint(fields=('task', 'version'), name='tasks_revision_unique_task_version'),
        ),
        migrations.AddConstraint(
            model_name='taskrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('task',), name='tasks_revision_one_active_per_task'),
        ),
        migrations.AddConstraint(
            model_name='taskrevision',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='tasks_revision_version_positive'),
        ),
        migrations.AddIndex(
            model_name='taskcheckpoint',
            index=models.Index(fields=['revision', 'order'], name='tasks_taskc_revisio_672eb7_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskcheckpoint',
            constraint=models.UniqueConstraint(fields=('revision', 'order'), name='tasks_checkpoint_unique_revision_order'),
        ),
        migrations.AddConstraint(
            model_name='taskcheckpoint',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 1)), name='tasks_checkpoint_order_positive'),
        ),
    ]
