# Generated by Django 6.0.4 on 2026-04-24 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('command_hint', models.CharField(blank=True, max_length=255)),
                ('success_criteria', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['revision__task__level__number', 'revision__task__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('objective', models.TextField()),
                ('steps', models.JSONField(blank=True, default=list)),
                ('expected_state', models.TextField(blank=True)),
                ('validator_notes', models.TextField(blank=True)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['task__level__number', 'task__order', '-version', 'id'],
            },
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_level_i_8e314d_idx',
            old_name='tasks_task_level_i_0f9522_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_slug_820535_idx',
            old_name='tasks_task_slug_7a6a80_idx',
        ),
        migrations.RenameIndex(
            model_name='taskasset',
            new_name='tasks_taska_task_id_44cb82_idx',
            old_name='tasks_taska_task_id_74c0f2_idx',
        ),
        migrations.AddField(
            model_name='taskrevision',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='taskcheckpoint',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='tasks.taskrevision'),
        ),
        migrations.AddIndex(
            model_name='taskrevision',
            index=models.Index(fields=['task', 'is_active'], name='tasks_taskr_task_id_7b7779_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskrevision',
            constraint=models.UniqueConstraint(fields=('task', 'version'), name='tasks_revision_unique_task_version'),
        ),
        migrations.AddConstraint(
            model_name='taskrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('task',), name='tasks_revision_one_active_per_task'),
        ),
        migrations.AddConstraint(
            model_name='taskrevision',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='tasks_revision_version_positive'),
        ),
        migrations.AddIndex(
            model_name='taskcheckpoint',
            index=models.Index(fields=['revision', 'order'], name='tasks_taskc_revisio_672eb7_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskcheckpoint',
            constraint=models.UniqueConstraint(fields=('revision', 'order'), name='tasks_checkpoint_unique_revision_order'),
        ),
        migrations.AddConstraint(
            model_name='taskcheckpoint',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 1)), name='tasks_checkpoint_order_positive'),
        ),
    ]
