# Generated by Django 6.0.4 on 2026-04-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskcheckpoint_taskrevision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcheckpoint',
            name='mapping_key',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
