# Generated by Django 6.0.4 on 2026-04-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_platform_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['level__number', 'platform', 'order', 'id']},
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_level_i_f94ffa_idx',
            old_name='tasks_task_level_4f8d77_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_platfor_9de46d_idx',
            old_name='tasks_task_platform_0f34a9_idx',
        ),
    ]
