# Generated by Django 6.0.4 on 2026-04-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_level_tasks_level_number_1_6_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='level',
            name='tasks_level_number_1_7',
        ),
        migrations.AddConstraint(
            model_name='level',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 1), ('number__lte', 8)), name='tasks_level_number_1_8'),
        ),
    ]
