# Generated by Django 6.0.4 on 2026-06-29 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('icon_path', models.CharField(blank=True, default='', max_length=255)),
                ('points_bonus', models.PositiveSmallIntegerField(default=0)),
                ('threshold_tasks', models.PositiveSmallIntegerField(default=0)),
                ('criterion_kind', models.CharField(choices=[('tasks_completed', 'Завершённые задачи'), ('quiz_easy_solved', 'Квиз: лёгкие'), ('quiz_medium_solved', 'Квиз: средние'), ('quiz_hard_solved', 'Квиз: сложные'), ('quiz_all_solved', 'Квиз: все вопросы'), ('streak_min', 'Серия ответов'), ('streak_flawless', 'Квиз без ошибок')], default='tasks_completed', max_length=32)),
                ('criterion_target', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='achievements.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-awarded_at'],
                'indexes': [models.Index(fields=['user', 'awarded_at'], name='achievement_user_id_4ac750_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'achievement'), name='achievements_unique_user_achievement')],
            },
        ),
    ]
