# Generated by Django 6.0.4 on 2026-04-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_achievement_threshold_tasks'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userachievement',
            new_name='achievement_user_id_4ac750_idx',
            old_name='achievement_user_id_179db8_idx',
        ),
        migrations.AddField(
            model_name='achievement',
            name='icon_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
