# Generated by Django 6.0.4 on 2026-04-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sandboxsession',
            new_name='sandbox_san_user_id_41806f_idx',
            old_name='sandbox_sa_user_id_a73fbe_idx',
        ),
        migrations.RenameIndex(
            model_name='sandboxsession',
            new_name='sandbox_san_expires_921f12_idx',
            old_name='sandbox_sa_expires_905f43_idx',
        ),
    ]
