"""Песочница и связанная логика плейграунда (фасад над подмодулями)."""

from .learn_ops import (
    HINT_UNLOCK_COSTS,
    NotEnoughPointsError,
    can_open_task,
    get_next_unlockable_task_for_user,
    unlock_hint,
    validate_task,
)
from .sandbox_ops import (
    SANDBOX_ALLOW_LOCAL_FALLBACK,
    SANDBOX_DOCKER_CPUS,
    SANDBOX_DOCKER_IMAGE,
    SANDBOX_DOCKER_MEMORY,
    SANDBOX_DOCKER_PIDS_LIMIT,
    SANDBOX_ENGINE,
    SANDBOX_ROOT,
    SANDBOX_TEXT_FILE_READ_MAX_BYTES,
    SANDBOX_TEXT_FILE_WRITE_MAX_BYTES,
    TERMINAL_PROMPT_PREFIX,
    CommandResult,
    audit_playground_repo_file,
    get_or_create_active_session,
    read_text_file_from_repo,
    reset_session,
    run_command,
    session_log,
    stop_session,
    write_text_file_to_repo,
)

__all__ = [
    "HINT_UNLOCK_COSTS",
    "NotEnoughPointsError",
    "SANDBOX_ALLOW_LOCAL_FALLBACK",
    "SANDBOX_DOCKER_CPUS",
    "SANDBOX_DOCKER_IMAGE",
    "SANDBOX_DOCKER_MEMORY",
    "SANDBOX_DOCKER_PIDS_LIMIT",
    "SANDBOX_ENGINE",
    "SANDBOX_ROOT",
    "SANDBOX_TEXT_FILE_READ_MAX_BYTES",
    "SANDBOX_TEXT_FILE_WRITE_MAX_BYTES",
    "TERMINAL_PROMPT_PREFIX",
    "CommandResult",
    "audit_playground_repo_file",
    "can_open_task",
    "get_next_unlockable_task_for_user",
    "get_or_create_active_session",
    "read_text_file_from_repo",
    "reset_session",
    "run_command",
    "session_log",
    "stop_session",
    "unlock_hint",
    "validate_task",
    "write_text_file_to_repo",
]
