# Generated by Django 6.0.4 on 2026-06-29 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('choice_0', models.CharField(max_length=512)),
                ('choice_1', models.CharField(max_length=512)),
                ('choice_2', models.CharField(max_length=512)),
                ('choice_3', models.CharField(max_length=512)),
                ('explanation_0', models.TextField(blank=True, default='')),
                ('explanation_1', models.TextField(blank=True, default='')),
                ('explanation_2', models.TextField(blank=True, default='')),
                ('explanation_3', models.TextField(blank=True, default='')),
                ('correct_index', models.PositiveSmallIntegerField()),
                ('difficulty', models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Тяжелый')], db_index=True, default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('correct_index__gte', 0), ('correct_index__lte', 3)), name='quiz_correct_index_range')],
            },
        ),
        migrations.CreateModel(
            name='QuizUserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_total', models.PositiveIntegerField(default=0)),
                ('correct_total', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('best_streak', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Статистика квиза',
                'verbose_name_plural': 'Статистика квиза',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts_total', models.PositiveIntegerField(default=0)),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('solved', models.BooleanField(db_index=True, default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='quiz.quizquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_question_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прогресс вопроса квиза',
                'verbose_name_plural': 'Прогресс вопросов квиза',
                'unique_together': {('user', 'question')},
            },
        ),
    ]
