# Generated by Django 6.0.4 on 2026-04-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizquestion_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='explanation_0',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='explanation_1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='explanation_2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='explanation_3',
            field=models.TextField(blank=True, default=''),
        ),
    ]
