"""Классификация сложности вопросов квиза по содержанию (не по позиции в списке)."""

from __future__ import annotations

# Базовые команды уровня «Git за 80% случаев» (Pro Git, гл. 2).
EASY_COMMANDS: frozenset[str] = frozenset(
    {
        "git init",
        "git add",
        "git status",
        "git commit",
        "git log",
        "git diff",
        "git clone",
        "git push",
        "git pull",
        "git fetch",
        "git branch",
        "git checkout",
        "git switch",
        "git merge",
        "git tag",
        "git remote",
        "git remote -v",
        "git remote add",
        "git help",
        "git version",
        "git mv",
        "git rm",
        "git show",
        "git checkout -b",
        "git switch -c",
        "git branch --show-current",
        "git push -u",
        "git log --oneline",
        "git log --graph",
        "git diff --staged",
        "git diff HEAD",
        "git push origin HEAD",
        "git merge origin/main",
        "git pull origin main",
        "git tag -l 'v*'",
        "git branch -m",
    }
)

HARD_COMMAND_MARKERS: tuple[str, ...] = (
    "bisect",
    "worktree",
    "submodule",
    "range-diff",
    "force-with-lease",
    "hash-object",
    "write-tree",
    "commit-tree",
    "cat-file",
    "update-ref",
    "symbolic-ref",
    "for-each-ref",
    "replace",
    "sparse-checkout",
    "bundle",
    "filter-repo",
    "send-email",
    "request-pull",
    "maintenance",
    "rerere",
    "interpret-trailers",
    "verify-commit",
    "verify-tag",
    "rebase --rebase-merges",
    "rebase --onto",
    "rebase --root",
    "push --push-option",
    "notes add",
    "notes show",
    "ls-tree",
    "update-index --chmod",
    "update-index --assume-unchanged",
    "merge --verify-signatures",
    "fetch origin refs/pull",
    "submodule foreach",
    "worktree remove",
    "bisect reset",
)

MEDIUM_COMMAND_MARKERS: tuple[str, ...] = (
    "rebase",
    "cherry-pick",
    "stash",
    "reset",
    "merge --",
    "restore",
    "revert",
    "reflog",
    "clean",
    "amend",
    "squash",
    "abort",
    "continue",
    "pull --rebase",
    "pull --ff",
    "pull --no-rebase",
    "fetch --prune",
    "push --delete",
    "branch -d",
    "branch -D",
    "branch --merged",
    "branch --no-merged",
    "branch --set-upstream",
    "tag -a",
    "describe",
    "blame",
    "grep",
    "log -S",
    "log --grep",
    "apply",
    "shortlog",
    "archive",
    "config pull",
    "config init.defaultBranch",
    "config --show-origin",
    "config core",
    "add -p",
    "commit -a",
    "commit --fixup",
    "commit --squash",
    "commit --allow-empty",
    "merge -X",
    "diff A",
    "log A..",
    "log --first-parent",
    "show-ref",
    "remote show",
    "remote remove",
    "clone --depth",
    "stash -u",
    "stash pop",
    "stash apply",
    "stash list",
    "stash drop",
    "switch --detach",
    "checkout --orphan",
    "checkout --track",
    "checkout -",
    "switch -",
    "merge --no-commit",
    "rebase --autosquash",
    "rebase --skip",
    "rebase --keep-empty",
    "cherry-pick --no-commit",
    "push --set-upstream",
    "push --tags",
    "push origin :",
    "tag -d",
    "log -p",
    "log --reverse",
    "log --stat",
    "log --decorate",
    "show --name-only",
    "diff --name-only",
    "diff --check",
    "diff --color-moved",
    "apply --check",
    "format-patch",
    "git am",
    "merge --signoff",
    "help -w",
)

# Темы «уровень 1» — основы Git / Pro Git гл. 1–3.
EASY_CONCEPT_MARKERS: tuple[str, ...] = (
    "три состоян",
    "три основных состоян",
    "staging area",
    "stage area",
    "индекс",
    "fast-forward",
    "gitignore",
    ".gitignore",
    "origin",
    "upstream",
    "ветк",
    "head",
    "clone",
    "снимк",
    "snapshots",
    "modified",
    "staged",
    "committed",
    "зафиксирован",
    "изменён",
    "изменен",
    "рабоч",
    "working directory",
    "git directory",
    "локальн",
    "офлайн",
    "sha-1",
    "целостност",
    "только добавляет данные",
    "git add",
    "git status",
    "git init",
    "git commit",
    "detached head",
    "tracking branch",
    "remote-tracking",
    "fetch",
    "pull = fetch",
    "bare repository",
    "ветки полностью локальны",
    "topic branch",
    "merge conflict markers",
    "<<<<<<<",
)

MEDIUM_CONCEPT_MARKERS: tuple[str, ...] = (
    "merge",
    "rebase",
    "конфликт",
    "reset --soft",
    "reset --mixed",
    "reset --hard",
    "три дерева",
    "revert",
    "stash",
    "cherry-pick",
    "amend",
    "squash",
    "no-ff",
    "integration-manager",
    "dictator",
    "pull request",
    "pre-commit",
    "pre-push",
    "hook",
    "workflow",
    "ours",
    "theirs",
    "three-way merge",
    "annotated tag",
    "lightweight tag",
    "shallow clone",
    "force-with-lease",
    "force push",
    "shared-вет",
    "публичн",
    "reflog",
    "rerere",
    "git mv",
    "git rm --cached",
    "gitattributes",
    "autocrlf",
    "format-patch",
    "git am",
    "shortlog",
    "signed-off",
    "sign-off",
    "submodule",
    "worktree",
    "sparse-checkout",
    "signed commit",
    "gpg",
    "pack file",
    "packfile",
    "github actions",
    "github pages",
    "ci",
)

HARD_CONCEPT_MARKERS: tuple[str, ...] = (
    "plumbing",
    "porcelain",
    "blob",
    "tree-объект",
    "commit-объект",
    "hash-object",
    "write-tree",
    "commit-tree",
    "cat-file",
    "packfiles",
    "pack file",
    "object database",
    "объект",
    ".git/objects",
    ".git/refs",
    "symbolic ref",
    "update-ref",
    "for-each-ref",
    "replace",
    "filter-repo",
    "bundle",
    "fsck",
    "git gc",
    "range-diff",
    "bisect",
    "server-side hook",
    "interpret-trailers",
    "verify-commit",
    "verify-tag",
    "update-index --chmod",
    "update-index --assume-unchanged",
    "update-index --skip-worktree",
    "merge --verify-signatures",
    "rebase --rebase-merges",
    "rebase --onto",
    "rebase --root",
    "push --push-option",
    "fetch origin refs/pull",
    "notes add",
    "git notes",
    "ls-tree",
    "rev-parse",
    "integration-manager",  # actually medium - remove
)


def _count_markers(text: str, markers: tuple[str, ...]) -> int:
    lowered = text.lower()
    return sum(1 for marker in markers if marker in lowered)


def classify_command_difficulty(cmd: str) -> str:
    """Сложность вопроса про конкретную git-команду."""
    if cmd in EASY_COMMANDS:
        return "easy"
    if any(marker in cmd for marker in HARD_COMMAND_MARKERS):
        return "hard"
    if any(marker in cmd for marker in MEDIUM_COMMAND_MARKERS):
        return "medium"
    return "easy"


def classify_concept_difficulty(prompt: str, correct: str) -> str:
    """Сложность концептуального вопроса по формулировке и правильному ответу."""
    text = f"{prompt} {correct}"
    hard = _count_markers(text, HARD_CONCEPT_MARKERS)
    medium = _count_markers(text, MEDIUM_CONCEPT_MARKERS)
    easy = _count_markers(text, EASY_CONCEPT_MARKERS)

    score = hard * 2 + medium - easy
    if score >= 3:
        return "hard"
    if score >= 1:
        return "medium"
    if easy >= 1 and hard == 0:
        return "easy"
    if medium >= 1:
        return "medium"
    return "easy"


def classify_question_difficulty(*, prompt: str, correct: str, cmd: str | None = None) -> str:
    if cmd is not None:
        return classify_command_difficulty(cmd)
    return classify_concept_difficulty(prompt, correct)
