# Generated by Django 6.0.4 on 2026-07-10 18:00

import apps.users.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudonym', models.CharField(max_length=10, unique=True, validators=[apps.users.validators.validate_pseudonym])),
                ('certificate_name', models.CharField(max_length=120)),
                ('learning_goal', models.CharField(choices=[('interview', 'Подготовка к собеседованию'), ('work', 'Для работы'), ('project', 'Pet-проект / своё'), ('interest', 'Просто интересно')], max_length=32)),
                ('knowledge_level', models.CharField(choices=[('none', 'Не пользовался'), ('basic', 'Базовый'), ('confident', 'Уверенный'), ('advanced', 'Продвинутый')], max_length=32)),
                ('job_role', models.CharField(blank=True, default='', max_length=120)),
                ('company_name', models.CharField(blank=True, default='', max_length=160)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('marketing_opt_in', models.BooleanField(default=False)),
                ('marketing_consent_at', models.DateTimeField(blank=True, null=True)),
                ('marketing_consent_version', models.CharField(blank=True, default='', max_length=32)),
                ('marketing_consent_text', models.TextField(blank=True, default='')),
                ('privacy_consent_at', models.DateTimeField()),
                ('privacy_consent_version', models.CharField(max_length=32)),
                ('privacy_consent_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_points', 'pseudonym'],
            },
        ),
        migrations.CreateModel(
            name='PointLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('source', models.CharField(choices=[('task_completion', 'Задача'), ('hint', 'Подсказка'), ('achievement', 'Достижение')], max_length=32)),
                ('ref_key', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='users_point_user_id_531882_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'source', 'ref_key'), name='users_pointledgerentry_unique_user_source_ref')],
            },
        ),
    ]
